name: "Profiler"

on:  # yamllint disable-line rule:truthy
  
  workflow_call:

   inputs:
      runner:
        required: true
        type: string

jobs:

  warmup:
    runs-on: [ "${{ inputs.runner }}" ]  
    steps:
    - name: Checking runner
      id: check_runner
      run: |
        echo "${{ inputs.runner }}"
