# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
env:
  runner_matrix: "{\"runner\":[ ubuntu-latest, macos-latest ]}"
  
jobs:
  warmup:
    runs-on: [ "${{ matrix.runner }}" ]
    strategy:
      matrix:
        runner: [ ubuntu-latest, macos-latest ]
    outputs:
      runner_config: ${{ steps.set_runner.outputs.runner_config }}
    
    steps:
    - name: Configuring runner
      id: set_runner
      run: echo "::set-output name=runner_config::$runner_matrix"

  build:
    needs: warmup
    runs-on: [ "${{ matrix.runner }}" ]
    strategy:
      matrix:
        runner: ${{ fromJSON(needs.warmup.outputs.runner_config) }}

    steps:
    - name: Check warmup
      run: |
        echo "${{ matrix.runner }}"
    - name: Sleep
      if: ${{ matrix.runner == 'ubuntu-latest' }} 
      run: |
        sleep 10

  test:
    needs: [warmup, build]
    runs-on: [ "${{ matrix.runner }}" ]
    strategy:
      matrix:
        runner: ${{ fromJSON(needs.warmup.outputs.runner_config) }}
    steps:
    - name: Check warmup
      run: echo "${{ matrix.runner }}"

  eval:
    needs: [warmup, test]
    if: ${{ always() }}
    runs-on: [ "${{ matrix.runner }}" ]
    strategy:
      matrix:
        runner: ${{ fromJSON(needs.warmup.outputs.runner_config) }}
    steps:
    - name: Check warmup
      run: echo "${{ matrix.runner }}"

  clean:
    needs: eval
    if: ${{ always() }}
    runs-on: [ "${{ matrix.runner }}" ]
    strategy:
      matrix:
        runner: ${{ fromJSON(needs.warmup.outputs.runner_config) }}
    steps:
    - name: Check warmup
      run: echo "${{ matrix.runner }}"
  
